### PR TITLE
#8 Re organize namespace

### PR DESCRIPTION
**Pull request by muroi**
Changes all process's namespace under masakari
- moves each config file to /etc/masakari and rename these to masakari-*.conf
- moves executable files to /opt/masakari/masakri-*
- renames log file name to masakari-*.log
- renames service name to masakari-*

### CODE REVIEW

**Comment by toshikazu0314** [comment]
Masakari controller should be named masakari-controller rather than masakari. After this change, I will update masakari-deploy to follow this pull request change.

**Comment by muroi** [comment]
@toshikazu0314 Thank you for reviewing. I agree it, so I change its namespace masakari to masakari-controller.

**Comment by sampathP** [comment]
1 comment on, https://github.com/ntt-sic/masakari/commit/b54e9eadcd1ef719c4babb29a5199af7ba0879e4
except that, looks good to me

**Comment by muroi** [comment]
@sampathP Thanks for rviewing. I updated the log file path. BTW, sorry, overwriting your comments..

**Comment by muroi** [comment]
close #8

**Pull request merged**
