### PR TITLE
Add setuptools and rpm setup capabilities

### PR DESCRIPTION
**Pull request by sampathP**
This patch add setuptools and rpm setup capabilities to masakari

Implement setuptools with pbr packaging feature for,
masakari-controller and masakari-instancemonitor.

rpm spec files for each project and located under,
[project_name]/rpmbuild/SPECS/*.spec
systemd scripts are under,
[project_name]/etc/systemd/system/[project_name].service

### CODE REVIEW

**Comment by sampathP** [comment]
To test this code,
Pull request to send to masakari-deploy for related deploy patch.
Or use following repo,
Repo: https://github.com/sampathP/masakari-deploy/
Branch: feature/centos-support
which is same as the above pull req.

**Comment by muroi** [comment]
Overall, LGTM. If possible, could you surround commands in README with ```sh ``` or something like that to easy to read in github page.

**Comment by sampathP** [comment]
@muroi Thank you for the review.
markdown the README is done.

**Comment by toshikazu0314** [comment]
looks good to me. Just need to resolve conflicts.

**Comment by sampathP** [comment]
Conflicts resolved

**Comment by sampathP** [comment]
#18 and this PR add .gitignore file but file content is slightly different.
I could rebase, but it will flush all the comment messages on this PR.
So, I will push a another patch for .gitignore after merge this.

**Pull request merged**
